/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.unicundi;

/**
 *
 * @author daiyd
 */
public class JPanelRectangulo extends javax.swing.JPanel {

    /**
     * Creates new form JPanelRectangulo
     */
    public JPanelRectangulo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coordenada3XRectangulo = new javax.swing.JTextField();
        coordenada3YRectangulo = new javax.swing.JTextField();
        botonCalcularRectangulo = new javax.swing.JButton();
        coordenada4XRectangulo = new javax.swing.JTextField();
        coordenada4YRectangulo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelAreaRectangulo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelPerimetroRectangulo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        coordenada1YRectangulo = new javax.swing.JTextField();
        coordenada1XRectangulo = new javax.swing.JTextField();
        coordenada2XRectangulo = new javax.swing.JTextField();
        coordenada2YRectangulo = new javax.swing.JTextField();
<<<<<<< Updated upstream
        jPanelGraficaRectangulo = new javax.swing.JPanel();
=======
        labelValidacionRectangulo = new javax.swing.JLabel();
>>>>>>> Stashed changes

        botonCalcularRectangulo.setText("Calcular");
        botonCalcularRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularRectanguloActionPerformed(evt);
            }
        });

        jLabel9.setText("El área del rectangulo es:");

        jLabel4.setText("C1");

        jLabel10.setText("El perímetro del rectangulo es:");

        jLabel5.setText("C2");

        labelAreaRectangulo.setText("Area");

        jLabel6.setText("C3");

        labelPerimetroRectangulo.setText("Perimetro");

        jLabel7.setText("C4");

        jLabel1.setText("Ingresa las coordenadas");

        jLabel2.setText("coordenadas x");

        jLabel3.setText("coordenadas y");

        coordenada2XRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coordenada2XRectanguloActionPerformed(evt);
            }
        });

<<<<<<< Updated upstream
        jPanelGraficaRectangulo.setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout jPanelGraficaRectanguloLayout = new javax.swing.GroupLayout(jPanelGraficaRectangulo);
        jPanelGraficaRectangulo.setLayout(jPanelGraficaRectanguloLayout);
        jPanelGraficaRectanguloLayout.setHorizontalGroup(
            jPanelGraficaRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );
        jPanelGraficaRectanguloLayout.setVerticalGroup(
            jPanelGraficaRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
=======
        labelValidacionRectangulo.setText("validacion");
>>>>>>> Stashed changes

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(coordenada1XRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(coordenada2XRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(coordenada3XRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(coordenada4XRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(31, 31, 31)
                                            .addComponent(jLabel7))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(botonCalcularRectangulo)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(coordenada1YRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(coordenada2YRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(coordenada3YRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(coordenada4YRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel9))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelAreaRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelPerimetroRectangulo))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(62, 62, 62))))
                    .addGroup(layout.createSequentialGroup()
<<<<<<< Updated upstream
                        .addComponent(jLabel1)
                        .addGap(62, 62, 62)))
                .addGap(26, 26, 26)
                .addComponent(jPanelGraficaRectangulo, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                .addContainerGap())
=======
                        .addGap(135, 135, 135)
                        .addComponent(labelValidacionRectangulo)))
                .addContainerGap(547, Short.MAX_VALUE))
>>>>>>> Stashed changes
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(coordenada1XRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coordenada2XRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coordenada3XRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coordenada4XRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(coordenada1YRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coordenada2YRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coordenada3YRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coordenada4YRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(botonCalcularRectangulo)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(labelAreaRectangulo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(labelPerimetroRectangulo))
<<<<<<< Updated upstream
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelGraficaRectangulo, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
=======
                .addGap(18, 18, 18)
                .addComponent(labelValidacionRectangulo)
                .addContainerGap(115, Short.MAX_VALUE))
>>>>>>> Stashed changes
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonCalcularRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularRectanguloActionPerformed
        // TODO add your handling code here:
        //coordenadas para poder calcular el área del rectángulo
        double areaRectangulo, perimetroRectangulo;
        int coorX1 = Integer.parseInt(coordenada1XRectangulo.getText());
        int coorX2 = Integer.parseInt(coordenada2XRectangulo.getText());
        int coorX3 = Integer.parseInt(coordenada3XRectangulo.getText());
        int coorX4 = Integer.parseInt(coordenada4XRectangulo.getText());
        int coorY1 = Integer.parseInt(coordenada1YRectangulo.getText());
        int coorY2 = Integer.parseInt(coordenada2YRectangulo.getText());
        int coorY3 = Integer.parseInt(coordenada3YRectangulo.getText());
        int coorY4 = Integer.parseInt(coordenada4YRectangulo.getText());

        //se envían las coordenadas al constructor
        Rectangulo rectangulo = new Rectangulo(coorX1, coorX2, coorX3, coorX4, coorY1, coorY2, coorY3, coorY4);
        rectangulo.dibujarFigura(jPanelGraficaRectangulo.getGraphics(), coorX1, coorX2, coorX3, coorX4, coorY1, coorY2, coorY3, coorY4);
        rectangulo.coordenadaALados();
        //se llaman las funciones para poder calcular el área y el perímetro del rectángulo
        rectangulo.area();
        rectangulo.perimetro();
        if (rectangulo.ladoA == rectangulo.ladoC && rectangulo.ladoB == rectangulo.ladoD) {
            areaRectangulo = rectangulo.area;
            perimetroRectangulo = rectangulo.perimetro;

            labelAreaRectangulo.setText(Double.toString(areaRectangulo));
            labelPerimetroRectangulo.setText(Double.toString(perimetroRectangulo));
        } else {
            labelValidacionRectangulo.setText("las coordenadas ingresadas no son un cuadrado");
        }

    }//GEN-LAST:event_botonCalcularRectanguloActionPerformed

    private void coordenada2XRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coordenada2XRectanguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coordenada2XRectanguloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalcularRectangulo;
    private javax.swing.JTextField coordenada1XRectangulo;
    private javax.swing.JTextField coordenada1YRectangulo;
    private javax.swing.JTextField coordenada2XRectangulo;
    private javax.swing.JTextField coordenada2YRectangulo;
    private javax.swing.JTextField coordenada3XRectangulo;
    private javax.swing.JTextField coordenada3YRectangulo;
    private javax.swing.JTextField coordenada4XRectangulo;
    private javax.swing.JTextField coordenada4YRectangulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelGraficaRectangulo;
    private javax.swing.JLabel labelAreaRectangulo;
    private javax.swing.JLabel labelPerimetroRectangulo;
    private javax.swing.JLabel labelValidacionRectangulo;
    // End of variables declaration//GEN-END:variables
}
