/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.unicundi;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author daiyd
 */
public class JPanelCuadrado extends javax.swing.JPanel {

    private JPanel jPanel = new JPanel();

    List<Figura> listaFigura = new ArrayList<Figura>();
    /**
     * Creates new form JPanelCuadrado
     */
    private int index = 0;
    double areaCuadrado, perimetroCuadrado;
    String difTriangulo;

    public JPanelCuadrado(int index) {
        this.index = index;
        initComponents();
    }

    JPanelCuadrado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        coordenada1YCuadrado = new javax.swing.JTextField();
        coordenada1XCuadrado = new javax.swing.JTextField();
        coordenada2XCuadrado = new javax.swing.JTextField();
        coordenada2YCuadrado = new javax.swing.JTextField();
        coordenada3XCuadrado = new javax.swing.JTextField();
        coordenada3YCuadrado = new javax.swing.JTextField();
        coordenada4XCuadrado = new javax.swing.JTextField();
        coordenada4YCuadrado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botonCalcularCuadrado = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelAreaCuadrado = new javax.swing.JLabel();
        labelPerimetroCuadrado = new javax.swing.JLabel();
        jPanelGraficaCuadrado = new javax.swing.JPanel();
        labelValidacionCuadrado = new javax.swing.JLabel();
        botonGuardarCuadrado = new javax.swing.JButton();
        jComboBoxMostrarFigura = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxColor = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();

        jLabel1.setText("Ingresa las coordenadas");

        jLabel2.setText("coordenadas x");

        jLabel3.setText("coordenadas y");

        coordenada2XCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coordenada2XCuadradoActionPerformed(evt);
            }
        });

        jLabel4.setText("C1");

        jLabel5.setText("C2");

        jLabel6.setText("C3");

        jLabel7.setText("C4");

        botonCalcularCuadrado.setText("Calcular");
        botonCalcularCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularCuadradoActionPerformed(evt);
            }
        });

        jLabel9.setText("El área es:");

        jLabel10.setText("El perímetro es:");

        labelAreaCuadrado.setText("Area");

        labelPerimetroCuadrado.setText("Perimetro");

        jPanelGraficaCuadrado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelGraficaCuadrado.setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout jPanelGraficaCuadradoLayout = new javax.swing.GroupLayout(jPanelGraficaCuadrado);
        jPanelGraficaCuadrado.setLayout(jPanelGraficaCuadradoLayout);
        jPanelGraficaCuadradoLayout.setHorizontalGroup(
            jPanelGraficaCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );
        jPanelGraficaCuadradoLayout.setVerticalGroup(
            jPanelGraficaCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        labelValidacionCuadrado.setText("validacion");

        botonGuardarCuadrado.setText("Guardar");
        botonGuardarCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarCuadradoActionPerformed(evt);
            }
        });

        jComboBoxMostrarFigura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMostrarFiguraActionPerformed(evt);
            }
        });

        jLabel8.setText("Mostrar Figura");

        jComboBoxColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rojo", "Amarillo", "Verde", "Azul" }));

        jLabel11.setText("Elija el color");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(coordenada1XCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(coordenada2XCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(coordenada3XCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(coordenada4XCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(31, 31, 31)
                                                .addComponent(jLabel7))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addComponent(coordenada1YCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(botonCalcularCuadrado))
                                                .addGap(28, 28, 28)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(botonGuardarCuadrado)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(coordenada2YCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(coordenada3YCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(coordenada4YCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jComboBoxColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(55, 55, 55)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxMostrarFigura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelValidacionCuadrado)
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAreaCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelPerimetroCuadrado))
                                .addGap(54, 54, 54)))))
                .addComponent(jPanelGraficaCuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(coordenada1XCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coordenada2XCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coordenada3XCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coordenada4XCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(coordenada1YCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coordenada2YCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coordenada3YCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coordenada4YCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCalcularCuadrado)
                    .addComponent(botonGuardarCuadrado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(labelAreaCuadrado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(labelPerimetroCuadrado))
                .addGap(18, 18, 18)
                .addComponent(labelValidacionCuadrado)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMostrarFigura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelGraficaCuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void coordenada2XCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coordenada2XCuadradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coordenada2XCuadradoActionPerformed

    private void botonCalcularCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularCuadradoActionPerformed
        // TODO add your handling code here:
        //coordenadas para poder calcular el cuadrado
        int coorX1 = Integer.parseInt(getCoordenada1XCuadrado().getText());
        int coorX2 = Integer.parseInt(getCoordenada2XCuadrado().getText());
        int coorX3 = Integer.parseInt(getCoordenada3XCuadrado().getText());
        int coorX4 = Integer.parseInt(getCoordenada4XCuadrado().getText());
        int coorY1 = Integer.parseInt(getCoordenada1YCuadrado().getText());
        int coorY2 = Integer.parseInt(getCoordenada2YCuadrado().getText());
        int coorY3 = Integer.parseInt(getCoordenada3YCuadrado().getText());
        int coorY4 = Integer.parseInt(getCoordenada4YCuadrado().getText());

        switch (getIndex()) {

            case 0:
                //se envían al constructor las coordenadas para poder hallar el +área y el perímetro del triángulo
                Triangulo triangulo = new Triangulo(coorX1, coorX2, coorX3, coorY1, coorY2, coorY3);
                triangulo.dibujarFigura(jPanelGraficaCuadrado.getGraphics(), coorX1, coorX2, coorX3, coorY1, coorY2, coorY3, jComboBoxColor.getSelectedItem().toString());
                triangulo.coordenadaALados();
                triangulo.perimetro();
                triangulo.area();
                triangulo.difTriangulos();
                areaCuadrado = triangulo.getArea();
                perimetroCuadrado = triangulo.getPerimetro();
                difTriangulo = triangulo.getDifTriangulo();

                //se muestran los resultados
                labelAreaCuadrado.setText(Double.toString(areaCuadrado));
                labelPerimetroCuadrado.setText(Double.toString(perimetroCuadrado));
                labelValidacionCuadrado.setText(difTriangulo);
                break;

            case 1:
                //se envían las coordenadas al constructor de la clase Cuadrado
                Cuadrado cuadrado = new Cuadrado(coorX1, coorX2, coorX3, coorX4, coorY1, coorY2, coorY3, coorY4);
                cuadrado.dibujarFigura(jPanelGraficaCuadrado.getGraphics(), coorX1, coorX2, coorX3, coorX4, coorY1, coorY2, coorY3, coorY4, jComboBoxColor.getSelectedItem().toString());

                //se llaman las funciones para poder calcular el área y el perímetro
                cuadrado.coordenadaALados();
                cuadrado.perimetro();
                cuadrado.area();
                if (cuadrado.getLadoA() == cuadrado.getLadoB()) {
                    //System.out.println(cuadrado.ladoA+"asdasd lado a");
                    areaCuadrado = cuadrado.getArea();
                    //System.out.println("area   "+areaCuadrado);
                    perimetroCuadrado = cuadrado.getPerimetro();
                    //se añaden al Label para mostrar en pantalla el área y el perímetro
                    labelAreaCuadrado.setText(Double.toString(areaCuadrado));
                    labelPerimetroCuadrado.setText(Double.toString(perimetroCuadrado));
                } else {
                    labelValidacionCuadrado.setText("las coordenadas ingresadas no son un cuadrado");
                }
                break;

            case 2:
//se envían las coordenadas al constructor

                Rectangulo rectangulo = new Rectangulo(coorX1, coorX2, coorX3, coorX4, coorY1, coorY2, coorY3, coorY4);

                //Graphics g;
                //g =rectangulo.dibujarPlano();
                rectangulo.dibujarFigura(jPanelGraficaCuadrado.getGraphics(), coorX1, coorX2, coorX3, coorX4, coorY1, coorY2, coorY3, coorY4);
                //rectangulo.dibujarPlano();
                rectangulo.coordenadaALados();
                //se llaman las funciones para poder calcular el área y el perímetro del rectángulo
                rectangulo.area();
                rectangulo.perimetro();
                if (rectangulo.getLadoA() == rectangulo.getLadoC() && rectangulo.getLadoB() == rectangulo.getLadoD()) {
                    areaCuadrado = rectangulo.getArea();
                    perimetroCuadrado = rectangulo.getPerimetro();
                    labelAreaCuadrado.setText(Double.toString(areaCuadrado));
                    labelPerimetroCuadrado.setText(Double.toString(perimetroCuadrado));
                } else {
                    labelValidacionCuadrado.setText("las coordenadas ingresadas no son un rectangulo");
                }
                break;

        }
        //System.out.println(coorX1+""+coorX2+""+coorX3+""+coorX4);


    }//GEN-LAST:event_botonCalcularCuadradoActionPerformed

    private void botonGuardarCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarCuadradoActionPerformed

        int coorX1 = Integer.parseInt(getCoordenada1XCuadrado().getText());
        int coorX2 = Integer.parseInt(getCoordenada2XCuadrado().getText());
        int coorX3 = Integer.parseInt(getCoordenada3XCuadrado().getText());
        int coorX4 = Integer.parseInt(getCoordenada4XCuadrado().getText());
        int coorY1 = Integer.parseInt(getCoordenada1YCuadrado().getText());
        int coorY2 = Integer.parseInt(getCoordenada2YCuadrado().getText());
        int coorY3 = Integer.parseInt(getCoordenada3YCuadrado().getText());
        int coorY4 = Integer.parseInt(getCoordenada4YCuadrado().getText());

        switch (getIndex()) {

            case 0:
                //se envían al constructor las coordenadas para poder hallar el +área y el perímetro del triángulo
                Triangulo triangulo = new Triangulo(coorX1, coorX2, coorX3, coorY1, coorY2, coorY3);
                listaFigura.add(triangulo);
                jComboBoxMostrarFigura.addItem("Triangulo");

                break;

            case 1:
                //se envían las coordenadas al constructor de la clase Cuadrado
                Cuadrado cuadrado = new Cuadrado(coorX1, coorX2, coorX3, coorX4, coorY1, coorY2, coorY3, coorY4);
                listaFigura.add(cuadrado);
                jComboBoxMostrarFigura.addItem("Cuadrado");
                break;

            case 2:
//se envían las coordenadas al constructor

                Rectangulo rectangulo = new Rectangulo(coorX1, coorX2, coorX3, coorX4, coorY1, coorY2, coorY3, coorY4);
                listaFigura.add(rectangulo);
                jComboBoxMostrarFigura.addItem("Rectangulo");

                break;

        }
    }//GEN-LAST:event_botonGuardarCuadradoActionPerformed

    private void jComboBoxMostrarFiguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMostrarFiguraActionPerformed

        Figura figura = listaFigura.get(jComboBoxMostrarFigura.getSelectedIndex());
        //int coorX1 = Integer.parseInt(((listaFigura.get(jComboBoxMostrarFigura.getSelectedIndex()))));
        int coorX1 = (int) (figura.getCoorX1());
        int coorX2 = (int) (figura.getCoorX2());
        int coorX3 = (int) (figura.getCoorX3());
        int coorX4 = (int) (figura.getCoorX4());
        int coorY1 = (int) (figura.getCoorY1());
        int coorY2 = (int) (figura.getCoorY2());
        int coorY3 = (int) (figura.getCoorY3());
        int coorY4 = (int) (figura.getCoorY4());
        int numeroFigura;
        if (jComboBoxMostrarFigura.getSelectedItem().toString().equals("Triangulo")) {
            numeroFigura = 0;
        } else if (jComboBoxMostrarFigura.getSelectedItem().toString().equals("Cuadrado")) {
            numeroFigura = 1;
        } else {
            numeroFigura = 2;
        }

        switch (numeroFigura) {

            case 0:
                ((Triangulo) (figura)).dibujarFigura(jPanelGraficaCuadrado.getGraphics(), coorX1, coorX2, coorX3, coorY1, coorY2, coorY3, jComboBoxColor.getSelectedItem().toString());
                //se envían al constructor las coordenadas para poder hallar el +área y el perímetro del triángulo

                //System.out.println(triangulo);
                ((Triangulo) (figura)).coordenadaALados();
                ((Triangulo) (figura)).perimetro();
                ((Triangulo) (figura)).area();
                ((Triangulo) (figura)).difTriangulos();
                areaCuadrado = ((Triangulo) (figura)).getArea();
                perimetroCuadrado = ((Triangulo) (figura)).getPerimetro();
                difTriangulo = ((Triangulo) (figura)).getDifTriangulo();

                //se muestran los resultados
                labelAreaCuadrado.setText(Double.toString(areaCuadrado));
                labelPerimetroCuadrado.setText(Double.toString(perimetroCuadrado));
                labelValidacionCuadrado.setText(difTriangulo);

                break;

            case 1:
                //se envían las coordenadas al constructor de la clase Cuadrado
                ((Cuadrado) (figura)).dibujarFigura(jPanelGraficaCuadrado.getGraphics(), coorX1, coorX2, coorX3, coorX4, coorY1, coorY2, coorY3, coorY4, jComboBoxColor.getSelectedItem().toString());

                //se llaman las funciones para poder calcular el área y el perímetro
                ((Cuadrado) (figura)).coordenadaALados();
                ((Cuadrado) (figura)).perimetro();
                ((Cuadrado) (figura)).area();
                if (((Cuadrado) (figura)).getLadoA() == ((Cuadrado) (figura)).getLadoB()) {
                    //System.out.println(cuadrado.ladoA+"asdasd lado a");
                    areaCuadrado = ((Cuadrado) (figura)).getArea();
                    //System.out.println("area   "+areaCuadrado);
                    perimetroCuadrado = ((Cuadrado) (figura)).getPerimetro();
                    //se añaden al Label para mostrar en pantalla el área y el perímetro
                    labelAreaCuadrado.setText(Double.toString(areaCuadrado));
                    labelPerimetroCuadrado.setText(Double.toString(perimetroCuadrado));
                } else {
                    labelValidacionCuadrado.setText("las coordenadas ingresadas no son un cuadrado");
                }
                break;

            case 2:
                //se envían las coordenadas al constructor

                ((Rectangulo) (figura)).dibujarFigura(jPanelGraficaCuadrado.getGraphics(), coorX1, coorX2, coorX3, coorX4, coorY1, coorY2, coorY3, coorY4);
                //rectangulo.dibujarPlano();
                ((Rectangulo) (figura)).coordenadaALados();
                //se llaman las funciones para poder calcular el área y el perímetro del rectángulo
                ((Rectangulo) (figura)).area();
                ((Rectangulo) (figura)).perimetro();
                if (((Rectangulo) (figura)).getLadoA() == ((Rectangulo) (figura)).getLadoC() && ((Rectangulo) (figura)).getLadoB() == ((Rectangulo) (figura)).getLadoD()) {
                    areaCuadrado = ((Rectangulo) (figura)).getArea();
                    perimetroCuadrado = ((Rectangulo) (figura)).getPerimetro();
                    labelAreaCuadrado.setText(Double.toString(areaCuadrado));
                    labelPerimetroCuadrado.setText(Double.toString(perimetroCuadrado));
                } else {
                    labelValidacionCuadrado.setText("las coordenadas ingresadas no son un rectangulo");
                }
                break;

        }


    }//GEN-LAST:event_jComboBoxMostrarFiguraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalcularCuadrado;
    private javax.swing.JButton botonGuardarCuadrado;
    private javax.swing.JTextField coordenada1XCuadrado;
    private javax.swing.JTextField coordenada1YCuadrado;
    private javax.swing.JTextField coordenada2XCuadrado;
    private javax.swing.JTextField coordenada2YCuadrado;
    private javax.swing.JTextField coordenada3XCuadrado;
    private javax.swing.JTextField coordenada3YCuadrado;
    private javax.swing.JTextField coordenada4XCuadrado;
    private javax.swing.JTextField coordenada4YCuadrado;
    private javax.swing.JComboBox jComboBoxColor;
    private javax.swing.JComboBox jComboBoxMostrarFigura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelGraficaCuadrado;
    private javax.swing.JLabel labelAreaCuadrado;
    private javax.swing.JLabel labelPerimetroCuadrado;
    private javax.swing.JLabel labelValidacionCuadrado;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the index
     */
    public int getIndex() {
        return index;
    }

    /**
     * @param index the index to set
     */
    public void setIndex(int index) {
        this.index = index;
    }

    /**
     * @return the coordenada1XCuadrado
     */
    public javax.swing.JTextField getCoordenada1XCuadrado() {
        return coordenada1XCuadrado;
    }

    /**
     * @param coordenada1XCuadrado the coordenada1XCuadrado to set
     */
    public void setCoordenada1XCuadrado(javax.swing.JTextField coordenada1XCuadrado) {
        this.coordenada1XCuadrado = coordenada1XCuadrado;
    }

    /**
     * @return the coordenada1YCuadrado
     */
    public javax.swing.JTextField getCoordenada1YCuadrado() {
        return coordenada1YCuadrado;
    }

    /**
     * @param coordenada1YCuadrado the coordenada1YCuadrado to set
     */
    public void setCoordenada1YCuadrado(javax.swing.JTextField coordenada1YCuadrado) {
        this.coordenada1YCuadrado = coordenada1YCuadrado;
    }

    /**
     * @return the coordenada2XCuadrado
     */
    public javax.swing.JTextField getCoordenada2XCuadrado() {
        return coordenada2XCuadrado;
    }

    /**
     * @param coordenada2XCuadrado the coordenada2XCuadrado to set
     */
    public void setCoordenada2XCuadrado(javax.swing.JTextField coordenada2XCuadrado) {
        this.coordenada2XCuadrado = coordenada2XCuadrado;
    }

    /**
     * @return the coordenada2YCuadrado
     */
    public javax.swing.JTextField getCoordenada2YCuadrado() {
        return coordenada2YCuadrado;
    }

    /**
     * @param coordenada2YCuadrado the coordenada2YCuadrado to set
     */
    public void setCoordenada2YCuadrado(javax.swing.JTextField coordenada2YCuadrado) {
        this.coordenada2YCuadrado = coordenada2YCuadrado;
    }

    /**
     * @return the coordenada3XCuadrado
     */
    public javax.swing.JTextField getCoordenada3XCuadrado() {
        return coordenada3XCuadrado;
    }

    /**
     * @param coordenada3XCuadrado the coordenada3XCuadrado to set
     */
    public void setCoordenada3XCuadrado(javax.swing.JTextField coordenada3XCuadrado) {
        this.coordenada3XCuadrado = coordenada3XCuadrado;
    }

    /**
     * @return the coordenada3YCuadrado
     */
    public javax.swing.JTextField getCoordenada3YCuadrado() {
        return coordenada3YCuadrado;
    }

    /**
     * @param coordenada3YCuadrado the coordenada3YCuadrado to set
     */
    public void setCoordenada3YCuadrado(javax.swing.JTextField coordenada3YCuadrado) {
        this.coordenada3YCuadrado = coordenada3YCuadrado;
    }

    /**
     * @return the coordenada4XCuadrado
     */
    public javax.swing.JTextField getCoordenada4XCuadrado() {
        return coordenada4XCuadrado;
    }

    /**
     * @param coordenada4XCuadrado the coordenada4XCuadrado to set
     */
    public void setCoordenada4XCuadrado(javax.swing.JTextField coordenada4XCuadrado) {
        this.coordenada4XCuadrado = coordenada4XCuadrado;
    }

    /**
     * @return the coordenada4YCuadrado
     */
    public javax.swing.JTextField getCoordenada4YCuadrado() {
        return coordenada4YCuadrado;
    }

    /**
     * @param coordenada4YCuadrado the coordenada4YCuadrado to set
     */
    public void setCoordenada4YCuadrado(javax.swing.JTextField coordenada4YCuadrado) {
        this.coordenada4YCuadrado = coordenada4YCuadrado;
    }

}
